language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go get -v github.com/robertkrimen/otto/otto # Download otto JS interpreter
  - yarn
script:
  - yarn run lint
  - yarn test
  - yarn run test:c
  - otto src/decoder.js # Run through otto (used by TTN)
  - otto src/encoder.js # Run through otto (used by TTN)
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
