language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
before_install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go get -v github.com/robertkrimen/otto/otto # Download otto JS interpreter
  - sudo apt-get install lcov rubygems
  - gem install coveralls-lcov
script:
  - yarn run lint
  - FORCE_COLOR=true yarn test
  - yarn run test:c
  - otto src/decoder.js # Run through otto (used by TTN)
  - otto src/encoder.js # Run through otto (used by TTN)
after_success:
  - yarn run coveralls
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} test/coverage.info # uploads to coveralls
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
